<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Tue, 04 Jan 2022 07:23:48 +0100
 */

$conf['title'] = 'KamWiki';
$conf['start'] = 'wiki';
$conf['lang'] = 'ru';
$conf['template'] = 'vector';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['proxy']['user'] = 'admin';
$conf['proxy']['pass'] = '<b>Mk1qUHpwUVY5aUFMLkJR';
