# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sat, 18 Dec 2021 04:39:08 +0000
*               @ALL          1
*               @user         8
