# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Sat, 18 Dec 2021 04:39:08 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

admin:$2y$10$Pe3Vx5sgJy5M0EERT2oQVO9SrVAvVhfaF88OWF5Nlp0hCS1dXIrcS:admin:vlybenetskii@gmail.com:admin,user
